[project]
name = "edm-mde-validation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dimx>=1.2.0",
    "edmkit>=0.0.12",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "pyedm>=2.5.6",
    "pytest>=9.1.1",
]

[dependency-groups]
dev = [
    "ruff>=0.16.3",
    "ty>=0.0.72",
]
